### ISSUE TITLE
Request for Explanation on "Registering Dataset" Step

### ISSUE THREAD

**Issue by anirbansaha96** [SaschaDittmann/MLOps-AzureCLI#37]
Hi Sascha, I came across your repository after watching your YouTube tutorial. Thanks a lot for this amazing content. I am not sure if raising a GitHub issue is the best way to resolve a query I have, but feel free to close it if you would rather have me reach out to you some other way.

So I have a doubt in the step "Registering Dataset". In [Lines 91-92](https://github.com/anirbansaha96/MLOps-AzureCLI/blob/master/azure-pipelines.yml#L91) of `azure-pipelines.yml`. 

```
sed "s/<default-datastore>/$(az ml datastore show-default -w $(azureml.workspaceName) -g $(azureml.resourceGroup) --query name -o tsv)/g" datasets/diabetes-dataset-specs.json > metadata/diabetes-dataset-specs.json
          az ml dataset register -w $(azureml.workspaceName) -g $(azureml.resourceGroup) -f metadata/diabetes-dataset-specs.json -t metadata/diabetes-dataset.json
```

* What exactly does the `sed` step accomplish?  
* When we pass the string `s/<default-datastore>/`, how exactly is the `<default-datastore>` part populated?
* What exactly do we mean by `datasets/diabetes-dataset-specs.json`: Since we did not have a file `diabetes-dataset-specs.json` or a folder `datasets\`?
*  What is the information that Azure ML is using to register the dataset when it is just using `metadata/diabetes-dataset-specs.json`

Thank you so much for your time! You may reach out to me on my [LinkedIn](https://www.linkedin.com/in/saha-anirban8/) if you prefer to help me out there instead of GitHub. 

Make a great day, and again thanks for the great tutorials!

**Comment by SaschaDittmann** [comment]
Hey Anirban,
I upgraded my original repo to use the Azure ML Dataset feature.
The specs file, you're looking for is [here](https://github.com/SaschaDittmann/MLOps-AzureCLI/blob/master/datasets/diabetes-dataset-specs.json)
This file also contains a reference to the datastore, which is used to store the csv files.
Since your datastore is different from mine, I added a placeholder in that file which I called "<default-datastore>".
The sed command replaces this placeholder with the actual datastore reference.
I hope this helps.
Best regards,
Sascha
